-- Connect to the database (create if it doesn't exist)
CONNECT 'jdbc:derby:IoTBayDB;create=true';

-- Create User table
CREATE TABLE USERS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    USER_TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

-- Create email Index
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

-- exit
EXIT; 